name: tmp

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches: 
      - '*'
  workflow_dispatch:


jobs:
  lint-docs:
    name: Lint Docs
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint docs
      uses: docker://avtodev/markdown-lint:v1 # fastest way
      with:
        config: './.markdownlint.yaml'
        args: './docs/MatrixOne'
